/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Token CSRF da mandare in X-XSRF-TOKEN
         * @description Da chiamare all'avvio e di nuovo dopo il login (il token cambia).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token corrente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CsrfTokenResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrazione (manda un codice di verifica via email) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Utente creato, stato PENDING_VERIFICATION */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verifica l'email con il codice di 6 cifre */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyRequest"];
                };
            };
            responses: {
                /** @description Account attivo, ora si può fare login */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invia un nuovo codice di verifica
         * @description Risponde 204 anche se l'email non esiste (non rivela chi è registrato). Massimo 3 ogni 15 minuti.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResendCodeRequest"];
                };
            };
            responses: {
                /** @description Richiesta accettata */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login (crea la sessione)
         * @description Dopo il 200 rifare `GET /api/auth/csrf`. Limite 5 tentativi per email e 30 per IP ogni 15 minuti.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login riuscito */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description Account non attivo: `code` = EMAIL_NOT_VERIFIED oppure ACCOUNT_DEACTIVATED */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["AccountNotActiveProblem"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Utente della sessione (200 = loggato, 401 = no) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Utente loggato */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout (invalida la sessione) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sessione chiusa */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eventi pubblicati e non ancora finiti, dal più vicino */
        get: {
            parameters: {
                query?: {
                    /** @description Testo nel titolo */
                    q?: string;
                    /** @description Città (uguale, senza maiuscole) */
                    city?: string;
                    /** @description Numero di pagina, da 0 */
                    page?: components["parameters"]["Page"];
                    /** @description Elementi per pagina (valori oltre 50 vengono ridotti a 50) */
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di eventi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageEventSummary"];
                    };
                };
            };
        };
        put?: never;
        /** Crea un evento (il proprietario è l'utente loggato) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventRequest"];
                };
            };
            responses: {
                /** @description Evento creato */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Segnaposto per la mappa pubblica (array, massimo 500) */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    city?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Segnaposto */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventPinResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Dettaglio evento (visibile anche se annullato) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Evento */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Modifica un evento (proprietario o MODERATOR)
         * @description Sostituisce tutto, scaletta e marker compresi (lista vuota o assente = nessuno).
         *     L'ordine di `lineup` è l'ordine della serata. I partecipanti ricevono una notifica EVENT_UPDATED.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventRequest"];
                };
            };
            responses: {
                /** @description Evento aggiornato */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /**
         * Cancella un evento senza partecipanti
         * @description Con ticket validi risponde 409 — in quel caso l'evento si annulla con /cancel.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Evento cancellato (anche le sue immagini su Cloudinary) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Annulla un evento (resta visibile come CANCELLED)
         * @description I partecipanti ricevono una notifica EVENT_CANCELLED. Ripetere la chiamata non fa nulla.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Evento annullato */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eventi creati dall'utente (anche passati e annullati) */
        get: {
            parameters: {
                query?: {
                    /** @description Numero di pagina, da 0 */
                    page?: components["parameters"]["Page"];
                    /** @description Elementi per pagina (valori oltre 50 vengono ridotti a 50) */
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di eventi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageEventSummary"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aggiunge una foto all'evento (massimo 10; la prima è la copertina) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": components["schemas"]["ImageUpload"];
                };
            };
            responses: {
                /** @description Foto caricata */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventImageResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                413: components["responses"]["PayloadTooLarge"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                imageId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Toglie una foto (la successiva diventa copertina) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    imageId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Foto rimossa */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/lineup/{artistId}/poster": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                /** @description `lineup[].artistId` dell'evento */
                artistId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Carica o sostituisce la locandina di un artista in scaletta */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    /** @description `lineup[].artistId` dell'evento */
                    artistId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": components["schemas"]["ImageUpload"];
                };
            };
            responses: {
                /** @description Riga di scaletta aggiornata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LineupEntryResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                413: components["responses"]["PayloadTooLarge"];
            };
        };
        /** Toglie la locandina */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    /** @description `lineup[].artistId` dell'evento */
                    artistId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Locandina rimossa */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/ai-description": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propone una descrizione migliore (non la salva)
         * @description Usa il testo inviato (o, se vuoto, la descrizione salvata) e la copertina.
         *     La proposta si applica con la PUT dell'evento. Mostrarla con textContent, mai come HTML.
         *     Modelli gratuiti: 503 frequente nei momenti di punta → pulsante "Riprova".
         *     Massimo 10 proposte riuscite ogni 15 minuti per utente.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AiDescriptionRequest"];
                };
            };
            responses: {
                /** @description Proposta */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiDescriptionResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["TooManyRequests"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cerca artisti per nome */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    /** @description Numero di pagina, da 0 */
                    page?: components["parameters"]["Page"];
                    /** @description Elementi per pagina (valori oltre 50 vengono ridotti a 50) */
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di artisti */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageArtist"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Crea un artista (qualsiasi utente loggato)
         * @description Gli artisti si creano anche da soli indicandoli per nome nella scaletta di un evento.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ArtistRequest"];
                };
            };
            responses: {
                /** @description Artista creato */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArtistResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Dettaglio artista */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Artista */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArtistResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Modifica un artista (MODERATOR) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ArtistRequest"];
                };
            };
            responses: {
                /** @description Artista aggiornato */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArtistResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        post?: never;
        /** Cancella un artista non presente in nessuna scaletta (MODERATOR) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Artista cancellato */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iscrizione all'evento (arriva il ticket via email) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ticket emesso */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description Già iscritto, oppure evento al completo */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}/tickets/me": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /** Il mio ticket per questo evento */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ticket */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Annulla la mia iscrizione (prima dell'inizio) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Iscrizione annullata */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /**
         * Partecipanti (li vedono proprietario, moderatori e gli altri partecipanti)
         * @description Serve a mandare richieste di amicizia a chi partecipa allo stesso evento.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Numero di pagina, da 0 */
                    page?: components["parameters"]["Page"];
                    /** @description Elementi per pagina (valori oltre 50 vengono ridotti a 50) */
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di partecipanti */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageParticipant"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** I miei ticket validi */
        get: {
            parameters: {
                query?: {
                    /** @description Numero di pagina, da 0 */
                    page?: components["parameters"]["Page"];
                    /** @description Elementi per pagina (valori oltre 50 vengono ridotti a 50) */
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di ticket */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageTicket"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Le mie notifiche, dalla più recente
         * @description Le nuove arrivano anche in tempo reale su STOMP `/user/queue/notifications`.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Numero di pagina, da 0 */
                    page?: components["parameters"]["Page"];
                    /** @description Elementi per pagina (valori oltre 50 vengono ridotti a 50) */
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di notifiche */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageNotification"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Numero di notifiche non lette (badge) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Contatore */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnreadCountResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Segna una notifica come letta */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Letta */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/events/{eventId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Messaggio del proprietario a tutti i partecipanti (notifica OWNER_MESSAGE) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OwnerMessageRequest"];
                };
            };
            responses: {
                /** @description Inviato */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friendships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** I miei amici (amicizie ACCEPTED) */
        get: {
            parameters: {
                query?: {
                    /** @description Numero di pagina, da 0 */
                    page?: components["parameters"]["Page"];
                    /** @description Elementi per pagina (valori oltre 50 vengono ridotti a 50) */
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di amici */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageFriend"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Richiesta di amicizia a un altro partecipante dello stesso evento */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FriendRequestCreate"];
                };
            };
            responses: {
                /** @description Richiesta inviata (notifica FRIEND_REQUEST al destinatario) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FriendRequestResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friendships/requests/received": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Richieste ricevute in attesa */
        get: {
            parameters: {
                query?: {
                    /** @description Numero di pagina, da 0 */
                    page?: components["parameters"]["Page"];
                    /** @description Elementi per pagina (valori oltre 50 vengono ridotti a 50) */
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di richieste */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageFriendRequest"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friendships/requests/sent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Richieste inviate in attesa */
        get: {
            parameters: {
                query?: {
                    /** @description Numero di pagina, da 0 */
                    page?: components["parameters"]["Page"];
                    /** @description Elementi per pagina (valori oltre 50 vengono ridotti a 50) */
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di richieste */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageFriendRequest"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friendships/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accetta una richiesta ricevuta (notifica FRIEND_ACCEPTED al mittente) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nuovo amico */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FriendResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friendships/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rifiuta una richiesta ricevuta */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rifiutata */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friendships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Toglie un amico o ritira una richiesta inviata
         * @description Lo storico della chat resta leggibile, ma non si possono più mandare messaggi.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rimossa */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inbox con l'ultimo messaggio e i non letti per ogni chat */
        get: {
            parameters: {
                query?: {
                    /** @description Numero di pagina, da 0 */
                    page?: components["parameters"]["Page"];
                    /** @description Elementi per pagina (valori oltre 50 vengono ridotti a 50) */
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di chat */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageChatSummary"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description id dell'amicizia (`chatId` / `friendshipId`) */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Storico dei messaggi, dal più recente
         * @description I messaggi nuovi arrivano via STOMP su `/user/queue/chat`; si inviano con `/app/chat.send`.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Numero di pagina, da 0 */
                    page?: components["parameters"]["Page"];
                    size?: number;
                };
                header?: never;
                path: {
                    /** @description id dell'amicizia (`chatId` / `friendshipId`) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di messaggi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageChatMessage"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Segna come letti i messaggi ricevuti in questa chat */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Letti */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Il mio profilo completo */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profilo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        /** Modifica i dati anagrafici (l'email non si cambia) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description Profilo aggiornato */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        post?: never;
        /**
         * Elimina l'account (anonimizzazione, D15)
         * @description Chiede la password. Chiude tutte le sessioni; l'avatar viene cancellato da Cloudinary.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeleteAccountRequest"];
                };
            };
            responses: {
                /** @description Account eliminato */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambia password (le altre sessioni vengono chiuse) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description Password cambiata */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Carica o sostituisce l'avatar */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": components["schemas"]["ImageUpload"];
                };
            };
            responses: {
                /** @description Profilo con il nuovo avatarUrl */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                413: components["responses"]["PayloadTooLarge"];
            };
        };
        /** Toglie l'avatar */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Avatar rimosso */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cerca utenti attivi per nome e cognome (almeno 2 caratteri) */
        get: {
            parameters: {
                query: {
                    q: string;
                    /** @description Numero di pagina, da 0 */
                    page?: components["parameters"]["Page"];
                    /** @description Elementi per pagina (valori oltre 50 vengono ridotti a 50) */
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di utenti */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageUserSummary"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Profilo pubblico di un utente */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Utente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserSummaryResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Elenco account con filtri (MODERATOR) */
        get: {
            parameters: {
                query?: {
                    /** @description Email, nome o cognome */
                    q?: string;
                    role?: components["schemas"]["Role"];
                    status?: components["schemas"]["UserStatus"];
                    /** @description Numero di pagina, da 0 */
                    page?: components["parameters"]["Page"];
                    /** @description Elementi per pagina (valori oltre 50 vengono ridotti a 50) */
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageAdminUser"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Dettaglio account (MODERATOR) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUserResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cambia il ruolo di un account (solo SUPERADMIN, non il proprio) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoleChangeRequest"];
                };
            };
            responses: {
                /** @description Account aggiornato */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUserResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/admin/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Attiva o disattiva un account (MODERATOR solo su USER; SUPERADMIN su tutti tranne sé)
         * @description Disattivare chiude subito le sessioni dell'utente.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StatusChangeRequest"];
                };
            };
            responses: {
                /** @description Account aggiornato */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUserResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/stato": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stato del servizio e del database */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Servizio attivo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example attivo */
                            servizio: string;
                            /** @example eventi */
                            database: string;
                            /** Format: date-time */
                            ora: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actuator/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check (usato da Render) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description UP */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example UP */
                            status: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetail: {
            /** @example about:blank */
            type: string;
            /** @example Bad Request */
            title: string;
            /** @example 400 */
            status: number;
            /**
             * @description Messaggio in italiano da mostrare
             * @example La data di inizio deve essere nel futuro
             */
            detail: string;
            /** @example /api/events */
            instance: string;
        };
        ValidationProblem: components["schemas"]["ProblemDetail"] & {
            /**
             * @description Presente solo per errori di validazione dei campi
             * @example {
             *       "province": "La provincia e' una sigla di 2 lettere"
             *     }
             */
            errors?: {
                [key: string]: string;
            };
        };
        AccountNotActiveProblem: components["schemas"]["ProblemDetail"] & {
            /** @enum {string} */
            code?: "EMAIL_NOT_VERIFIED" | "ACCOUNT_DEACTIVATED";
        };
        PageMeta: {
            /** @example 20 */
            size: number;
            /** @example 0 */
            number: number;
            /**
             * Format: int64
             * @example 42
             */
            totalElements: number;
            /** @example 3 */
            totalPages: number;
        };
        ImageUpload: {
            /**
             * Format: binary
             * @description JPEG, PNG o WebP, massimo 5 MB
             */
            file: string;
        };
        CsrfTokenResponse: {
            /** @example X-XSRF-TOKEN */
            headerName: string;
            token: string;
        };
        /** @enum {string} */
        Role: "USER" | "MODERATOR" | "SUPERADMIN";
        /** @enum {string} */
        UserStatus: "PENDING_VERIFICATION" | "ACTIVE" | "DEACTIVATED";
        /** @enum {string} */
        EventStatus: "PUBLISHED" | "CANCELLED";
        /** @enum {string} */
        TicketStatus: "VALID" | "CANCELLED";
        /** @enum {string} */
        MarkerKind: "ENTRANCE" | "EXIT" | "EMERGENCY_EXIT";
        /** @enum {string} */
        NotificationType: "EVENT_UPDATED" | "EVENT_CANCELLED" | "OWNER_MESSAGE" | "NEW_PARTICIPANT" | "FRIEND_REQUEST" | "FRIEND_ACCEPTED";
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            firstName: string;
            lastName: string;
            /**
             * Format: date
             * @description Nel passato
             */
            birthDate: string;
            /** @description Deve essere true */
            privacyAccepted: boolean;
        };
        VerifyRequest: {
            /** Format: email */
            email: string;
            /** @example 482913 */
            code: string;
        };
        ResendCodeRequest: {
            /** Format: email */
            email: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            role: components["schemas"]["Role"];
            avatarUrl: string | null;
        };
        EventRequest: {
            title: string;
            description?: string | null;
            /**
             * Format: date-time
             * @description Nel futuro (in modifica si può lasciare quella già salvata)
             */
            startsAt: string;
            /**
             * Format: date-time
             * @description Non prima di startsAt
             */
            endsAt?: string | null;
            venueName?: string | null;
            address: string;
            city: string;
            /** @example MI */
            province?: string | null;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            /** @description null = senza limite; non sotto gli iscritti attuali */
            maxParticipants?: number | null;
            /** @description In ordine di esibizione; artisti indicati per nome (creati se non esistono), senza ripetizioni */
            lineup?: components["schemas"]["LineupEntryRequest"][] | null;
            markers?: components["schemas"]["MarkerRequest"][] | null;
        };
        LineupEntryRequest: {
            artistName: string;
            /** Format: date-time */
            performanceStart?: string | null;
            /** Format: date-time */
            performanceEnd?: string | null;
        };
        MarkerRequest: {
            kind: components["schemas"]["MarkerKind"];
            label?: string | null;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        EventSummaryResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string | null;
            venueName: string | null;
            city: string;
            province: string | null;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            status: components["schemas"]["EventStatus"];
            /** @description Prima immagine dell'evento */
            coverUrl: string | null;
        };
        EventPinResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date-time */
            startsAt: string;
            city: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        EventResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string | null;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string | null;
            venueName: string | null;
            address: string;
            city: string;
            province: string | null;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            maxParticipants: number | null;
            /**
             * Format: int64
             * @description Ticket validi
             */
            participants: number;
            status: components["schemas"]["EventStatus"];
            owner: components["schemas"]["OwnerResponse"];
            images: components["schemas"]["EventImageResponse"][];
            /** @description Ordinata per performanceOrder */
            lineup: components["schemas"]["LineupEntryResponse"][];
            markers: components["schemas"]["MarkerResponse"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OwnerResponse: {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName: string;
            avatarUrl: string | null;
        };
        EventImageResponse: {
            /** Format: uuid */
            id: string;
            url: string;
            /** @description 0 = copertina */
            sortOrder: number;
        };
        LineupEntryResponse: {
            /** Format: uuid */
            artistId: string;
            artistName: string;
            genre: string | null;
            imageUrl: string | null;
            /** @description 1 = apre la serata */
            performanceOrder: number;
            /** Format: date-time */
            performanceStart: string | null;
            /** Format: date-time */
            performanceEnd: string | null;
            posterUrl: string | null;
        };
        MarkerResponse: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["MarkerKind"];
            label: string | null;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        AiDescriptionRequest: {
            /** @description Bozza da migliorare; vuota = descrizione salvata */
            text: string | null;
        };
        AiDescriptionResponse: {
            /** @description Testo generato, da mostrare con textContent */
            proposal: string;
        };
        ArtistRequest: {
            /** @description Unico senza distinguere maiuscole */
            name: string;
            genre?: string | null;
            bio?: string | null;
            /** @description Solo link http o https */
            imageUrl?: string | null;
        };
        ArtistResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            genre: string | null;
            bio: string | null;
            imageUrl: string | null;
        };
        TicketResponse: {
            /** Format: uuid */
            id: string;
            /** @description Codice del ticket (anche nell'email) */
            code: string;
            status: components["schemas"]["TicketStatus"];
            /** Format: date-time */
            issuedAt: string;
            event: components["schemas"]["EventSummaryResponse"];
        };
        ParticipantResponse: {
            /**
             * Format: uuid
             * @description id utente, da usare come addresseeId
             */
            id: string;
            firstName: string;
            lastName: string;
            avatarUrl: string | null;
        };
        NotificationResponse: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["NotificationType"];
            title: string;
            body: string;
            /** Format: uuid */
            eventId: string | null;
            /** Format: date-time */
            readAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        UnreadCountResponse: {
            /** Format: int64 */
            unread: number;
        };
        OwnerMessageRequest: {
            title: string;
            body: string;
        };
        UserSummaryResponse: {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName: string;
            avatarUrl: string | null;
        };
        FriendRequestCreate: {
            /**
             * Format: uuid
             * @description Utente a cui chiedere l'amicizia
             */
            addresseeId: string;
            /**
             * Format: uuid
             * @description Evento a cui partecipate entrambi
             */
            eventId: string;
        };
        FriendRequestResponse: {
            /** Format: uuid */
            id: string;
            user: components["schemas"]["UserSummaryResponse"];
            /** Format: uuid */
            eventId: string | null;
            eventTitle: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        FriendResponse: {
            /**
             * Format: uuid
             * @description È anche l'id della chat
             */
            friendshipId: string;
            friend: components["schemas"]["UserSummaryResponse"];
            /** Format: date-time */
            since: string;
            /** Format: int64 */
            unreadMessages: number;
        };
        /** @description Stesso formato dei messaggi ricevuti via STOMP su /user/queue/chat */
        ChatMessageResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            friendshipId: string;
            /** Format: uuid */
            senderId: string;
            content: string;
            /** Format: date-time */
            sentAt: string;
            /** Format: date-time */
            readAt: string | null;
        };
        ChatSummaryResponse: {
            /** Format: uuid */
            chatId: string;
            user: components["schemas"]["UserSummaryResponse"];
            /** @description false se l'amicizia è stata tolta o l'altro account non è attivo */
            canWrite: boolean;
            lastMessage: components["schemas"]["ChatMessageResponse"] | null;
            /** Format: int64 */
            unreadMessages: number;
        };
        AddressDto: {
            street: string | null;
            city: string | null;
            postalCode: string | null;
            province: string | null;
            /** @example IT */
            country: string | null;
        } | null;
        ProfileResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            /** Format: date */
            birthDate: string;
            address: components["schemas"]["AddressDto"];
            phone: string | null;
            avatarUrl: string | null;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            createdAt: string;
        };
        UpdateProfileRequest: {
            firstName: string;
            lastName: string;
            /** Format: date */
            birthDate: string;
            phone?: string | null;
            address?: components["schemas"]["AddressDto"];
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        DeleteAccountRequest: {
            password: string;
        };
        AdminUserResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["UserStatus"];
            /** Format: date-time */
            emailVerifiedAt: string | null;
            /** Format: date-time */
            anonymizedAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        RoleChangeRequest: {
            role: components["schemas"]["Role"];
        };
        StatusChangeRequest: {
            /** @enum {string} */
            status: "ACTIVE" | "DEACTIVATED";
        };
        PageEventSummary: {
            content: components["schemas"]["EventSummaryResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        PageArtist: {
            content: components["schemas"]["ArtistResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        PageTicket: {
            content: components["schemas"]["TicketResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        PageParticipant: {
            content: components["schemas"]["ParticipantResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        PageNotification: {
            content: components["schemas"]["NotificationResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        PageFriend: {
            content: components["schemas"]["FriendResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        PageFriendRequest: {
            content: components["schemas"]["FriendRequestResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        PageChatSummary: {
            content: components["schemas"]["ChatSummaryResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        PageChatMessage: {
            content: components["schemas"]["ChatMessageResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        PageUserSummary: {
            content: components["schemas"]["UserSummaryResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        PageAdminUser: {
            content: components["schemas"]["AdminUserResponse"][];
            page: components["schemas"]["PageMeta"];
        };
    };
    responses: {
        /** @description Dati non validi (con `errors` campo → messaggio) o operazione non ammessa */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description Non loggato (o credenziali sbagliate nel login) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Senza permesso, oppure header X-XSRF-TOKEN mancante o scaduto */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Non esiste o non è visibile all'utente */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Conflitto con lo stato attuale */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description File oltre i 5 MB */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Troppe richieste; riprovare dopo i secondi indicati */
        TooManyRequests: {
            headers: {
                /** @description Secondi di attesa */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Servizio esterno non disponibile (es. AI satura o non configurata) */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        Id: string;
        EventId: string;
        /** @description Numero di pagina, da 0 */
        Page: number;
        /** @description Elementi per pagina (valori oltre 50 vengono ridotti a 50) */
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
